In [1]:
import numpy as np

In [2]:
#Sliced list is a copy
py_list = [1, 2, 3, 4, 5]
copy_list = py_list[1:4] #[2, 3, 4]
copy_list[1] = 333

print(copy_list)
print(py_list)

#Sliced array is a view
np_arr = np.array([1, 2, 3, 4, 5])
view_arr = np_arr[1:4] #[2, 3, 4]
view_arr[1] = 333

print(view_arr)
print(np_arr)

#Creating a copy
copy_arr = np_arr[1:4].copy() #[2, 3, 4]
copy_arr[2] = 444
print(copy_arr)
print(np_arr)

[2, 333, 4]
[1, 2, 3, 4, 5]
[  2 333   4]
[  1   2 333   4   5]
[  2 333 444]
[  1   2 333   4   5]
