In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)

reshaped = arr.reshape((2, 3))
print(reshaped, reshaped.shape)

flattened = reshaped.flatten() #converts 2D => 1D
print(flattened, flattened.shape)

(6,)
[[1 2 3]
 [4 5 6]] (2, 3)
[1 2 3 4 5 6] (6,)
